/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CountDown: typeof import('./../src/components/count-down/index.vue')['default']
    EntryItem: typeof import('./../src/components/entry-item/index.vue')['default']
    GridList: typeof import('./../src/components/grid-list/index.vue')['default']
    MyTimer: typeof import('./../src/components/my-timer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
